### ISSUE TITLE
Binary tag values

### ISSUE THREAD

**Issue by slimsag** [opentracing/api-golang#12]
I saw in the docs for SetTag:

```
    // Adds a tag to the span. The `value` is immediately coerced into a string
    // using fmt.Sprint().
    //
    // If there is a pre-existing tag set for `key`, it is overwritten.
    SetTag(key string, value interface{}) Span
```

I presume this was to intentionally not allow binary `[]byte` tag values? Was there discussion around this that I missed, and could anyone link me to it?

**Comment by bensigelman** [comment]
There was no discussion about it that I'm aware of... For what it's worth, I was more concerned with the `value` not-being a nested type (i.e., not a struct) and less concerned with it being a string or a `[]byte`.

Do you have a specific pre-existing use-case for `[]byte`, by the way? I can imagine some for programmatic APIs that run over trace data.

**Comment by slimsag** [comment]
Currently in Appdash we allow encoding any arbitrary `struct` value, where the value is an arbitrary `[]byte` payload provided by the user.

In specific, this is very useful because clients can attach gob-encoded `struct` payloads with a span and our frontend/web UI can opt-in to rendering these payloads specially instead of just in a standard "key: value" display that we might use otherwise. We don't use this feature very extensively right now... so we wouldn't be at a strict loss without it... but I do think it would open up many possibilities in general.

For example, I might sent a space-efficient binary stack trace with a span and want to unpack it into a text form for display in the UX. I do suppose I could e.g. base64 encode during such a situation, but that seems wasteful unless we have a good reason to not support binary values.

**Comment by yurishkuro** [comment]
I like that, @slimsag. Where do you encode the rendering hint? Is it in the tag name, or in the binary blob itself?

Also, how portable is this approach?  I don't think you can encode Go struct from Java, for example.

**Comment by slimsag** [comment]
@yurishkuro Yes, the rendering hint is in the tag name. We consider the tag name to be the "data type name", e.g. "HTTPRequest" would unmarshal into a `HTTPRequest struct`. Portability is not a problem if you choose an encoding type that is language-agnostic. Protobuf etc would all do fine.

**Comment by bensigelman** [comment]
I am convinced that we should support `[]byte` payloads for these tag annotations. How do we want to express it in the API? (`interface{}` is tricky since I'm not aware of a surefire way to convert an arbitrary `interface{}` into a `[]byte`) It would make me sad to add more methods, but I guess we could add `SetBinaryTag(key string, value []byte)` in parallel to the current `SetTag(...)`.

**Comment by yurishkuro** [comment]
cf. https://github.com/uber-common/opentracing-go/blob/master/span.go#L54

`interface{}` should be ok. I think it's up to tracing system to support (or drop) different value types, and to decide how to serialize them. A tracer may also be configured with pluggable formatters for certain value types. Ultimately it's up to the tracing system what it wants to do with the values, how to stored them in storage, make searchable, etc., so I don't know how much we can do for portability here.

**Comment by yurishkuro** [comment]
@slimsag I think this is now addressed. Good to close?

**Comment by slimsag** [comment]
Yes, I think we're OK to close this now.

**Comment by adriancole** [comment]
I feel generally positive about this, though mixed because it requires coordination. Ex. binary is harder than json as you have no default rendering mode. Unless I'm missing something, this means that we are defaulting to a higher level of coordination. The good news is that might encourage better reuse of standard namespaces!
