### ISSUE TITLE
Metadata keys cannot contain dashes

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/api-golang#13]
Just ran into a stupid issue. With Python WSGI, the http requests are converted into an `environment` dictionary, where besides prepending `HTTP_` to each request header WSGI also changes all dashes to underscores. That means if we use individual headers with a custom prefix to propagate user metadata, a WSGI server will receive those custom headers with underscores and won't have any way to reconstruct the original name.

Do we want to restrict the metadata keys to be CGI-env compatible strings?

**Comment by yurishkuro** [comment]
Or maybe it's the other way around - we should prohibit underscores, since they are not always passed through middleware.

http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names

I've seen instrumentation code that takes WSGI environment and does `replace('_', '-')` to expose "normal" http headers to the client code.

**Comment by bensigelman** [comment]
(just wanted to mention that I'm planning to make this change in the near future -- been bogged down with other stupid stuff!)

**Comment by bensigelman** [comment]
I like the idea of requiring all keys to match the regex `(?i:[a-z][-a-z]*)`... We can always be more permissive!

**Comment by bensigelman** [comment]
#14

**Comment by adriancole** [comment]
yeah, like favoring http header interop
