### ISSUE TITLE
debug flag

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/api-golang#20]
EDIT: the actual use case: a mobile developer has a toggle in the app that allows him to mark all requests the app makes to the server with "please trace" flag (e.g. http header or by other means). When the server receives such request and starts a new trace, it wants to mark that trace as "debug" to ensure that it is preserved regardless of the sampling decisions.

----
It would be nice for start_trace method to accept an optional debug flag. Ultimately, all tracing systems will have to do some form of sampling, either before or after the trace. A debug flag allows users to force the sampling of the trace regardless of other sampling decisions.

While we can handle debug flag as an optional tag using the approach in #19, for systems that make upfront sampling decisions there are certain housekeeping operations that can be skipped (for efficiency reasons) when the span is being created if the tracer decided not to sample it. Examples may include adding various tags to the span, that would be a waste of CPU clocks and memory for non-sampled span. Therefore, setting a debug flag after span creation may cause those spans to be missing the tags they would've gotten had it been known that they are going to be sampled.

**Comment by bensigelman** [comment]
Why not make debug-ness the responsibility of the Recorder? (That's what I'd had in mind) I completely agree that it's an important use case, but I'm not clear why it needs to be part of the StartTrace signature.

**Comment by yurishkuro** [comment]
I updated the description with the actual use case. The "debug"-ness is a property of an individual trace controlled by some custom property of the incoming request. It's not a mode of the Recorder, the same tracer/recorded should be able to accommodate both debug and non-debug traces.

**Comment by bensigelman** [comment]
Dapper dealt with this by propagating a "trace_mask" along with the "trace_id" and "span_id" over the wire. The mask encoded information about the sampling rate and whether there was an "explicit" sampling or the usual pseudorandom sampling.

Somewhat related: I think there's definitely value (is there even an alternative??) to propagating whether and how the current context is sampled for systems like zipkin/dapper that do a priori sampling, I wouldn't want to equate that with a "debug" context. I.e., maybe all debug contexts are explicitly sampled, but all explicitly sampled contexts are not debug contexts.

**Comment by yurishkuro** [comment]
Zipkin also encodes debug / sampled as bits in the `flags` trace context field, but that doesn't help with the question of how the debug bit gets set when starting a new trace.

Interesting point on debug context, it indeed can mean more than just forced sampling, but how do we mark a context as debug? Users don't even have a say in context creation, all they do is call start_trace.

**Comment by bensigelman** [comment]
In golang, how about just `myTracer.StartTrace("opname").TraceContext().SetTraceTag("debug", "true")`? I.e., this seems like precisely the sort of thing we should be able to accomplish with trace tags / metadata.

**Comment by yurishkuro** [comment]
Sure, that's the simplest way, but as I mentioned, StartTrace() may already do some data collection, or rather *not* do it because the sampler turned down the new trace.

**Comment by bensigelman** [comment]
Ah, I see what you're saying, and I think you raise a good point. It's an edge case but one we should be able to support (at least in a "make the hard things possible" sort of way).

Something similar to `StartTraceWithTags(operationName string, traceTags map[string]string)`? Or `StartTraceWithContext(opName string, ctx TraceContext)`? (I like the latter more than the former, though neither makes me feel cheerful about API clutter)

**Comment by yurishkuro** [comment]
If you're open to extending the API in such manner, then I have slight preference for the former, because forcing instrumentation to create context manually is a lot more work than passing a debug=true attribute. Root context can only be created from the Source, and instrumentation doesn't even need to be exposed to the concept of the Source. Note that API clutter is primarily a Go issue only, in Python I would just do 
```
def start_trace(self, operation_name, **trace_tags)
```

BTW, as I was converting our Python to OTAPI naming, I kept the name `metadata` instead of `trace tags`, with methods `context.set_metadata(key, value)`. I like that it clearly separates key/values on the Context from tags on the Span and on the Recorder (which also ultimately become part of the span). I.e. tags are per-span, and stored out of band, thus are relatively cheap, while metadata is per trace, and propagates in-band.

**Comment by bensigelman** [comment]
(Agreed that this is easy in python, Java, js, etc, etc...)

At the moment there's little distinction between the two things I proposed since TraceContext per se doesn't really expose anything beyond SetTag at `StartSpan()`-time. If we add other capabilities to TraceContext, though – or helpers like the ones in `ext/` – that might change. I also don't feel strongly but still think it'd be preferable to take a TraceContext since it's more general and this is not the common case.

Re `metadata` vs `trace tags`: On the one hand, I also don't love `trace tags` since they aren't even compliant with the `opentracing.Tags` type (string -> string, the key restrictions, etc). That said, the term "metadata" is so general: I wish we could come up with something self-descriptive. I have sat here for a few minutes and came up empty, though :)

**Comment by yurishkuro** [comment]
Do you have some examples in mind what other functions might be added to the trace context?

Just read through wikipedia on "metadata", no revelations either. Strictly speaking, span tags are also metadata of spans, depends on where we draw the line what the span data is. Having said that, when I mention "context metadata" to people, they usually grasp right away what I mean. 

Another possible term is "attribute". We're propagating a context, and context has attributes. The word "attribute" seems more tightly coupled with the containing entity than "tag": tag is external to the entity (ie metadata, damn), while attribute is internal, inseparable.

**Comment by bensigelman** [comment]
"Attribute" seems better than "metadata" to me. What it still doesn't convey (I doubt any common word does) is how these tracecontext-level key:value pairs propagate. But I can live with Attribute for sure.

By the way, as an optimization I could imagine restricting attribute *setting* to Span construction time... This would allow the span's TraceContext to be immutable and thus lock-free for reads. (I don't like optimizing without a hotspot in a profile, though)

**Comment by yurishkuro** [comment]
hm, requiring all context attributes to be known upfront may be unrealistic. I can imaging a scenario where some security credentials are retrieved/calculated and added to the context after the trace has started. Like you I am not too worried about optimizing for locks until we need to.

**Comment by yurishkuro** [comment]
let's go with attributes then, this is a fairly common term that implies propagation / permanence, e.g. in HttpSessions etc.

**Comment by bensigelman** [comment]
(re knowing context attrs up-front: the implication would be to start a sub-span if need be)

**Comment by bensigelman** [comment]
Sounds good to me re "Trace Attributes". So, before closing this, we want to:
- `%s/TraceTag/TraceAttribute/g`
- make it possible to add trace attributes as part of `StartSpan` (in golang I'd still like to enable this by allowing a user-provided `TraceContext`)

**Comment by yurishkuro** [comment]
want to share the actual instrumentation code in Python:

```python

    def before_request(request, tracer):
        context = tracer.unmarshal_trace_context_str_dict(
            trace_context_id=request.headers, 
            attributes=request.headers
        )
        operation = request.operation
        if context is None:
            span = tracer.start_trace(operation_name=operation)
        else:
            span = tracer.join_trace(operation_name=operation, parent_trace_context=context)
        # add various tags from request
        return span
```

In order to support debug flag, I think the main piece would change like this:

```python
        if context is None:
            context = tracer.new_root_trace_context()
            if request.is_debug():
                context.set_trace_attribute("debug", True)
            span = tracer.start_span_with_context(operation_name=operation, trace_context=context)
        else:
            span = tracer.join_trace(operation_name=operation, parent_trace_context=context)
```

i.e. `tracer.start_trace()` is not used

**Comment by bensigelman** [comment]
^^^ makes sense... I like the look of `start_span_with_context` in this code, I hope it works for you?

**Comment by yurishkuro** [comment]
Yeah, I think it works. It bothers me that we don't seem to need `start_trace` anymore :smile: but I think it has its use for making easy things easy. FWIW, we've had a round of NodeJS apps instrumentation, with the help of app owners, and they really didn't want to write the code like above, we ended up providing a helper function like `getSpanFromHeaders`.

I'm going to close this issue.

**Comment by adriancole** [comment]
late to the party, but I think there's a nuance about "debug"

In zipkin, "debug" flag was something the user initiates (ex. before a trace starts!). "sampled" was a part of the propagation context, ex after the span started. IOTW, "debug" is requested by the user, but "sampled" is a transport mandate.

debug flag: https://github.com/twitter/finagle/blob/92b19e00db570d81cebbe686ecd80c6b4eb0d17a/finagle-http/src/main/scala/com/twitter/finagle/http/Codec.scala#L296
discussion about sampling:
https://github.com/openzipkin/zipkin-java/issues/52#issuecomment-167039593
