### ISSUE TITLE
Serializing trace context into binary protocols

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/api-golang#7]
I am interested in making [TChannel](https://github.com/uber/tchannel/blob/master/docs/protocol.md) implementations instrumented with opentracing API. The tracing is built into the protocol as a first-class citizen, the "trace ID" is accessible at a fixed position in the frame without parsing the whole request, which is critical when bouncing the requests through the routers to allow routers to participate in the traces. The current limitation of 64:64:64:8 bit length will be lifted in future revs, but the limitation of a fixed length will remain.

The trace context marshaller currently does not expose separate serialization for a trace ID, only for the whole context with metadata. 
 # should we create dedicated methods to serialize just the trace ID as a binary blob?
 # can we impose a certain limit on the size of that blob?

**Comment by bensigelman** [comment]
It sounds like the metadata can't be guaranteed to fit given the fixed (and presumably small) length. As such, could you substitute a custom Marshaler+Unmarshaler that skips the trace tags / metadata?

Or is there somewhere aside from that narrow region where the metadata could go? (Sounds unlikely given what you've indicated)

- Ben (mobile)

**Comment by yurishkuro** [comment]
Specifically in TChannel protocol the trace ID is encoded in a fixed position with a fixed length, so that routers can access and update it efficiently. It also supports arbitrary app headers where I expect metadata to go to, but it's not being parsed out by the routers. There are different ways we can support it, one is by splitting the methods, another is to change the binary marshaller to return a tuple, e.g.
```Go 
func MarshalTraceContextBinary(tcid TraceContext) (contextId []byte, metadata []byte)
```
yet another way is to define an optional interface that a TraceContextMarshaler can implement, that exposes split contextID+metadata methods, then TChannel would only work with tracing systems that support that extra interface.

Personally, I think since the metadata (tags) is already separated in the context API itself, it's not a stretch to have marshallers treat contextID and metadata separately, at least in binary marshaller.

**Comment by bensigelman** [comment]
I like that too. The reason I separated the id proper from the metadata a
few revs ago was because only the latter is actually needed to *identify* a
span. So there is a clear semantic division, and it's fine with me to reify
that. I'll make that change before Monday (or at least send out the PR).

On Saturday, December 5, 2015, Yuri Shkuro <notifications@github.com> wrote:

> Specifically in TChannel protocol the trace ID is encoded in a fixed
> position with a fixed length, so that routers can access and update it
> efficiently. It also supports arbitrary app headers where I expect metadata
> to go to, but it's not being parsed out by the routers. There are different
> ways we can support it, one is by splitting the methods, another is to
> change the binary marshaller to return a tuple, e.g.
>
> func MarshalTraceContextBinary(tcid TraceContext) (contextId []byte, metadata []byte)
>
> yet another way is to define an optional interface that a
> TraceContextMarshaler can implement, that exposes split contextID+metadata
> methods, then TChannel would only work with tracing systems that support
> that extra interface.
>
> Personally, I think since the metadata (tags) is already separated in the
> context API itself, it's not a stretch to have marshallers treat contextID
> and metadata separately, at least in binary marshaller.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/api-golang/issues/7#issuecomment-162244308>
> .
>


-- 
Sent via mobile

**Comment by yurishkuro** [comment]
I think this is good to close.

**Comment by bensigelman** [comment]
sgtm!

**Comment by adriancole** [comment]
This seems sound
